#!/bin/sh

scriptpath=$( cd "$(dirname "$0")" ; pwd -P )

dafny="$scriptpath/../../../local-dafny/Scripts/dafny"

if [ -z "${DAFNY_BINARY}" ]; then
    latestDafny="$dafny"
else
    latestDafny="${DAFNY_BINARY}"
fi
dafnyVerify="$latestDafny verify --resource-limit=100000000 --disable-nonlinear-arithmetic --cores=10"

files="$scriptpath/../../lib/* $scriptpath/../hosts.dfy $scriptpath/../types.dfy $scriptpath/distributedSystem.dfy $scriptpath/spec.dfy $scriptpath/messageInvariants.dfy $scriptpath/monotonicityInvariants.dfy $scriptpath/applicationProof.dfy"

echo "Verifying $files" | tr " " "\n"

time $dafnyVerify $files