#!/bin/sh

scriptpath=$( cd "$(dirname "$0")" ; pwd -P )

dafny="$scriptpath/../../../local-dafny/Scripts/dafny"

dafnyFootprint="$dafny /genFootprint"
dafnyMsgInv="$dafny /msgMonoInvs"
if [ -z "${DAFNY_BINARY}" ]; then
    latestDafny="$dafny"
else
    latestDafny="${DAFNY_BINARY}"
fi
dafnyVerify="$latestDafny verify --resource-limit=100000000 --disable-nonlinear-arithmetic --cores=10"

files="$scriptpath/../../lib/* $scriptpath/../hosts.dfy $scriptpath/../types.dfy $scriptpath/distributedSystem.dfy $scriptpath/spec.dfy $scriptpath/messageInvariantsAutogen.dfy $scriptpath/monotonicityInvariantsAutogen.dfy $scriptpath/customMessageInvariants.dfy $scriptpath/applicationProofDemo.dfy"

rm -f $scriptpath/footprintsAutogen.json $scriptpath/messageInvariantsAutogen.dfy $scriptpath/monotonicityInvariantsAutogen.dfy

echo "Generating footprints"
$dafnyFootprint "$scriptpath/distributedSystem.dfy" > footprints.log

echo "Generating invariants"
$dafnyMsgInv "$scriptpath/customMessageInvariants.dfy" > autoInvs.log

echo "Verifying $files" | tr " " "\n"

time $dafnyVerify $files